


/*Pasos*/
/*crear la tabla de errores y auditoria*/
/*crear el sp*/
/*Ejecutar el sp y parsarle como parametro el nombre de la bdd texto*/


/*Tabla de errores*/

CREATE TABLE TABLA_ERRORES 
(
		ID INT IDENTITY(1,1), 
		NUMERO_DE_ERROR VARCHAR(400) NOT NULL,
		MENSAJE_DE_ERROR VARCHAR(400) NOT NULL,
		FECHA_DE_CREACION DATETIME NOT NULL,
		USUARIO VARCHAR (400) NOT NULL,
		USUARIO_ID VARCHAR(400) DEFAULT SYSDATETIME()
)


/*Tabla auditoria*/

CREATE TABLE TABLA_AUDITORIA
(

		ID_OBJETO  INT IDENTITY (1,1),
		NOMBRE_BASE_DE_DATOS VARCHAR(100)  ,
		NOMBRE_SCHEMA VARCHAR (100)  ,
		NOMBRE_OBJETO VARCHAR(1000) DEFAULT ' --- ',
		TIPO_DE_DATO VARCHAR(100),
		TIENE_FK VARCHAR(4000) DEFAULT 'No' ,
		TIENE_PK VARCHAR(4000) DEFAULT 'No' ,
		TIENE_PK_COMPUESTA VARCHAR(4000) DEFAULT 'No' ,
		TIENE_FK_COMPUESTA VARCHAR(4000) DEFAULT 'No' ,
		ACEPTA_PARAMETROS VARCHAR(4000) DEFAULT 'No' ,
		FECHA_CONSULTA DATETIME DEFAULT SYSDATETIME()
)


/*DROP TABLE TABLA_AUDITORIA;*/








CREATE PROCEDURE MISP @NOMBREBDD  VARCHAR (4000) = '0'
AS
BEGIN
	BEGIN TRAN
	BEGIN TRY
		
		/*Veo la cantidad de bases de datos que existen con ese nombre*/
		DECLARE @CANTIDA_DE_DATABASES NVARCHAR(500) ;
		SELECT  @CANTIDA_DE_DATABASES =  COUNT(database_id)
		FROM SYS.DATABASES
		WHERE NAME = @NOMBREBDD;
		IF @CANTIDA_DE_DATABASES = '0'
		BEGIN
			RAISERROR('La base de datos que quieres analizar no existe',16,1);
		END
		ELSE
		/*Aca tendria que ir la query del use*/

			
		declare @QUERY_USE nvarchar(4000);
		set @QUERY_USE = 'use ' + @NOMBREBDD ;
		exec sp_sqlexec @QUERY_USE;
	
		

		/*Esta tabla va  a ser de existencia temporal , se usa para mostrar nada mas*/
		CREATE TABLE OBJETOS_DE_LA_BASE_DE_DATOS(
		ID_OBJETO  TINYINT IDENTITY (1,1),
		NOMBRE_BASE_DE_DATOS VARCHAR(100)  ,
		NOMBRE_SCHEMA VARCHAR (100)  ,
		NOMBRE_OBJETO VARCHAR(1000) DEFAULT ' --- ',
		TIPO_DE_DATO VARCHAR(100),
		TIENE_FK VARCHAR(4000) DEFAULT 'No' ,
		TIENE_PK VARCHAR(4000) DEFAULT 'No' ,
		TIENE_PK_COMPUESTA VARCHAR(4000) DEFAULT 'No' ,
		TIENE_FK_COMPUESTA VARCHAR(4000) DEFAULT 'No' ,
		ACEPTA_PARAMETROS VARCHAR(4000) DEFAULT 'No' 
		);
		

		/*En estas variables de va a guardar la info de los objetos*/
		DECLARE @NOMBRE_OBJETO VARCHAR(4000) = NULL;
		DECLARE @NOMBRE_SCHEMA VARCHAR(4000) = NULL;
		DECLARE @NOMBRE_TIPO VARCHAR(4000) = NULL;
	

		/*Voy a ver si existen tablas*/
		DECLARE @CANTIDAD_TABLAS VARCHAR;
		SELECT @CANTIDAD_TABLAS =  COUNT(TABLE_SCHEMA)
		FROM INFORMATION_SCHEMA.TABLES ;
		
		
		/*Si hay tablas voy a insertarlas en la tabla general*/
		IF @CANTIDAD_TABLAS <> '0'
		BEGIN
		
			
			/*Voy a crear un cursos para recorrer lo objetos que sean tablas*/
			DECLARE @QUERY NVARCHAR(3000) ;
			SET @QUERY = '
			DECLARE CURSOR_TABLAS CURSOR SCROLL FOR 
			SELECT TABLE_SCHEMA,TABLE_NAME,TABLE_TYPE FROM '+ @NOMBREBDD +'.INFORMATION_SCHEMA.TABLES where TABLE_NAME <>  ' + CHAR(39) + 'OBJETOS_DE_LA_BASE_DE_DATOS'  + CHAR(39) ;
			EXECUTE sp_executesql @QUERY
			OPEN CURSOR_TABLAS
			/*ver si anda*/
			FETCH NEXT FROM CURSOR_TABLAS INTO @NOMBRE_SCHEMA,@NOMBRE_OBJETO,@NOMBRE_TIPO;
			
			WHILE @@FETCH_STATUS = 0 /*Mientras alla tablas se va a recorrer y se van a agregar objetos-tablas a la tabla general*/
			BEGIN
				/*PARA VER CANTIDAD DE PK POR TABLA*/
				
				declare @Select NVARCHAR(4000);
				DECLARE @CANTIDAD_PK_TABLA VARCHAR(4000);
				
		

				SET @Select = 'SELECT @CANTIDAD_PK_TABLA = COUNT(A.CONSTRAINT_TYPE)
				FROM ' +@NOMBREBDD+'.INFORMATION_SCHEMA.TABLE_CONSTRAINTS AS A JOIN ' +@NOMBREBDD+ '.INFORMATION_SCHEMA.TABLES AS B ON A.TABLE_NAME = B.TABLE_NAME 
				WHERE A.TABLE_NAME = ' + CHAR(39)+@NOMBRE_OBJETO + CHAR(39) + ' AND A.CONSTRAINT_TYPE=' +CHAR(39)+'PRIMARY KEY'+CHAR(39);
			
				EXECUTE SP_EXECUTESQL	@Select,
				N'@CANTIDAD_PK_TABLA INT OUTPUT',
				@CANTIDAD_PK_TABLA=@CANTIDAD_PK_TABLA OUTPUT
					
				


				/*
				SELECT @CANTIDAD_PK_TABLA = COUNT(A.CONSTRAINT_TYPE)
				FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS AS A JOIN  INFORMATION_SCHEMA.TABLES AS B ON A.TABLE_NAME = B.TABLE_NAME 
				WHERE A.TABLE_NAME = @NOMBRE_OBJETO AND A.CONSTRAINT_TYPE='PRIMARY KEY';*/

				DECLARE @Select2 NVARCHAR(4000);
				DECLARE @CANTIDAD_FK_TABLA VARCHAR(4000);
				

				SET @Select2 = 'SELECT @CANTIDAD_FK_TABLA = COUNT(A.CONSTRAINT_TYPE)
				FROM ' +@NOMBREBDD+'.INFORMATION_SCHEMA.TABLE_CONSTRAINTS AS A JOIN ' +@NOMBREBDD+ '.INFORMATION_SCHEMA.TABLES AS B ON A.TABLE_NAME = B.TABLE_NAME 
				WHERE A.TABLE_NAME = '+ CHAR(39) + @NOMBRE_OBJETO + CHAR(39) + ' AND A.CONSTRAINT_TYPE=' +CHAR(39)+'FOREIGN KEY'+CHAR(39);
				EXECUTE SP_EXECUTESQL	@Select2,
				N'@CANTIDAD_FK_TABLA INT OUTPUT',
				
				@CANTIDAD_FK_TABLA=@CANTIDAD_FK_TABLA OUTPUT

				/*
				SELECT @CANTIDAD_FK_TABLA = COUNT(A.CONSTRAINT_TYPE)
				FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS AS A JOIN  INFORMATION_SCHEMA.TABLES AS B ON A.TABLE_NAME = B.TABLE_NAME 
				WHERE A.TABLE_NAME = @NOMBRE_OBJETO AND A.CONSTRAINT_TYPE='FOREIGN KEY';
				*/
				

				/*Inserto en la tabla general las tablas*/
				/*No tiene ni pk ni fk*/
				IF @CANTIDAD_PK_TABLA = 0 or @CANTIDAD_PK_TABLA = ''
				BEGIN
					IF @CANTIDAD_FK_TABLA = 0 or @CANTIDAD_FK_TABLA = ''
					BEGIN
						INSERT INTO OBJETOS_DE_LA_BASE_DE_DATOS (NOMBRE_BASE_DE_DATOS,NOMBRE_SCHEMA,NOMBRE_OBJETO,TIPO_DE_DATO,ACEPTA_PARAMETROS)
						VALUES (@NOMBREBDD,@NOMBRE_SCHEMA,@NOMBRE_OBJETO,@NOMBRE_TIPO,'---');
					END
				END

				/*Tiene pk simple*/
				IF @CANTIDAD_PK_TABLA = 1
				BEGIN
					/*NO TIENE FK*/ 
					IF @CANTIDAD_FK_TABLA = 0 or @CANTIDAD_FK_TABLA = ''
					BEGIN
						INSERT INTO OBJETOS_DE_LA_BASE_DE_DATOS (NOMBRE_BASE_DE_DATOS,NOMBRE_SCHEMA,NOMBRE_OBJETO,TIPO_DE_DATO,ACEPTA_PARAMETROS,TIENE_PK)
						VALUES (@NOMBREBDD,@NOMBRE_SCHEMA,@NOMBRE_OBJETO,@NOMBRE_TIPO,'---','Si');
					END
					/*Tiene FK simple*/
					IF @CANTIDAD_FK_TABLA = 1
					BEGIN
						INSERT INTO OBJETOS_DE_LA_BASE_DE_DATOS (NOMBRE_BASE_DE_DATOS,NOMBRE_SCHEMA,NOMBRE_OBJETO,TIPO_DE_DATO,ACEPTA_PARAMETROS,TIENE_PK,TIENE_FK)
						VALUES (@NOMBREBDD,@NOMBRE_SCHEMA,@NOMBRE_OBJETO,@NOMBRE_TIPO,'---','Si','Si');
					END
					/*Tiene Fk compuesta*/
					IF @CANTIDAD_FK_TABLA > 1
					BEGIN
						INSERT INTO OBJETOS_DE_LA_BASE_DE_DATOS (NOMBRE_BASE_DE_DATOS,NOMBRE_SCHEMA,NOMBRE_OBJETO,TIPO_DE_DATO,ACEPTA_PARAMETROS,TIENE_PK,TIENE_FK,TIENE_PK_COMPUESTA,TIENE_FK_COMPUESTA)
						VALUES (@NOMBREBDD,@NOMBRE_SCHEMA,@NOMBRE_OBJETO,@NOMBRE_TIPO,'---','Si','Si','No','Si');
					END
				END

				/*Tiene Pk compuesta*/
				IF @CANTIDAD_PK_TABLA > 1
				BEGIN
					/*NO TIENE FK*/ 
					IF @CANTIDAD_FK_TABLA = 0 or @CANTIDAD_FK_TABLA = ''
					BEGIN
						INSERT INTO OBJETOS_DE_LA_BASE_DE_DATOS (NOMBRE_BASE_DE_DATOS,NOMBRE_SCHEMA,NOMBRE_OBJETO,TIPO_DE_DATO,ACEPTA_PARAMETROS,TIENE_PK,TIENE_FK,TIENE_PK_COMPUESTA)
						VALUES (@NOMBREBDD,@NOMBRE_SCHEMA,@NOMBRE_OBJETO,@NOMBRE_TIPO,'---','Si','No','Si');
					END
					/*Tiene FK simple*/
					IF @CANTIDAD_FK_TABLA = 1
					BEGIN
						INSERT INTO OBJETOS_DE_LA_BASE_DE_DATOS (NOMBRE_BASE_DE_DATOS,NOMBRE_SCHEMA,NOMBRE_OBJETO,TIPO_DE_DATO,ACEPTA_PARAMETROS,TIENE_PK,TIENE_FK,TIENE_PK_COMPUESTA)
						VALUES (@NOMBREBDD,@NOMBRE_SCHEMA,@NOMBRE_OBJETO,@NOMBRE_TIPO,'---','Si','Si','Si');
					END
					/*Tiene Fk compuesta*/
					IF @CANTIDAD_FK_TABLA > 1
					BEGIN
						INSERT INTO OBJETOS_DE_LA_BASE_DE_DATOS (NOMBRE_BASE_DE_DATOS,NOMBRE_SCHEMA,NOMBRE_OBJETO,TIPO_DE_DATO,ACEPTA_PARAMETROS,TIENE_PK,TIENE_FK,TIENE_PK_COMPUESTA,TIENE_FK_COMPUESTA)
						VALUES (@NOMBREBDD,@NOMBRE_SCHEMA,@NOMBRE_OBJETO,@NOMBRE_TIPO,'---','Si','Si','Si','Si');
					END
				END
				
				/*Tiene fk simple*/
				IF @CANTIDAD_PK_TABLA = 1
				BEGIN
					/*NO TIENE PK*/ 
					IF @CANTIDAD_PK_TABLA = 0 or @CANTIDAD_PK_TABLA = ''
					BEGIN
						INSERT INTO OBJETOS_DE_LA_BASE_DE_DATOS (NOMBRE_BASE_DE_DATOS,NOMBRE_SCHEMA,NOMBRE_OBJETO,TIPO_DE_DATO,ACEPTA_PARAMETROS,TIENE_PK,TIENE_FK)
						VALUES (@NOMBREBDD,@NOMBRE_SCHEMA,@NOMBRE_OBJETO,@NOMBRE_TIPO,'---','No','Si');
					END
					/*Tiene PK simple*/
					IF @CANTIDAD_PK_TABLA = 1
					BEGIN
						INSERT INTO OBJETOS_DE_LA_BASE_DE_DATOS (NOMBRE_BASE_DE_DATOS,NOMBRE_SCHEMA,NOMBRE_OBJETO,TIPO_DE_DATO,ACEPTA_PARAMETROS,TIENE_PK,TIENE_FK)
						VALUES (@NOMBREBDD,@NOMBRE_SCHEMA,@NOMBRE_OBJETO,@NOMBRE_TIPO,'---','Si','Si');
					END
					/*Tiene PK compuesta*/
					IF @CANTIDAD_PK_TABLA > 1
					BEGIN
						INSERT INTO OBJETOS_DE_LA_BASE_DE_DATOS (NOMBRE_BASE_DE_DATOS,NOMBRE_SCHEMA,NOMBRE_OBJETO,TIPO_DE_DATO,ACEPTA_PARAMETROS,TIENE_PK,TIENE_FK,TIENE_PK_COMPUESTA,TIENE_FK_COMPUESTA)
						VALUES (@NOMBREBDD,@NOMBRE_SCHEMA,@NOMBRE_OBJETO,@NOMBRE_TIPO,'---','Si','Si','Si','No');
					END
				END		
				
				/*Tiene FK compuesta*/
				IF @CANTIDAD_PK_TABLA > 1
				BEGIN
					/*NO TIENE PK*/ 
					IF @CANTIDAD_PK_TABLA = 0 or @CANTIDAD_PK_TABLA = ''
					BEGIN
						INSERT INTO OBJETOS_DE_LA_BASE_DE_DATOS (NOMBRE_BASE_DE_DATOS,NOMBRE_SCHEMA,NOMBRE_OBJETO,TIPO_DE_DATO,ACEPTA_PARAMETROS,TIENE_PK,TIENE_FK,TIENE_PK_COMPUESTA,TIENE_FK_COMPUESTA)
						VALUES (@NOMBREBDD,@NOMBRE_SCHEMA,@NOMBRE_OBJETO,@NOMBRE_TIPO,'---','Si','No','No','Si');
					END
					/*Tiene PK simple*/
					IF @CANTIDAD_PK_TABLA = 1
					BEGIN
						INSERT INTO OBJETOS_DE_LA_BASE_DE_DATOS (NOMBRE_BASE_DE_DATOS,NOMBRE_SCHEMA,NOMBRE_OBJETO,TIPO_DE_DATO,ACEPTA_PARAMETROS,TIENE_PK,TIENE_FK,TIENE_PK_COMPUESTA,TIENE_FK_COMPUESTA)
						VALUES (@NOMBREBDD,@NOMBRE_SCHEMA,@NOMBRE_OBJETO,@NOMBRE_TIPO,'---','Si','Si','No','Si');
					END
					/*Tiene PK compuesta*/
					IF @CANTIDAD_PK_TABLA > 1
					BEGIN
						INSERT INTO OBJETOS_DE_LA_BASE_DE_DATOS (NOMBRE_BASE_DE_DATOS,NOMBRE_SCHEMA,NOMBRE_OBJETO,TIPO_DE_DATO,ACEPTA_PARAMETROS,TIENE_PK,TIENE_FK,TIENE_PK_COMPUESTA,TIENE_FK_COMPUESTA)
						VALUES (@NOMBREBDD,@NOMBRE_SCHEMA,@NOMBRE_OBJETO,@NOMBRE_TIPO,'---','Si','Si','Si','Si');
					END
				END
					
				
				FETCH NEXT FROM CURSOR_TABLAS INTO @NOMBRE_SCHEMA,@NOMBRE_OBJETO,@NOMBRE_TIPO;
			END
			CLOSE CURSOR_TABLAS;
			DEALLOCATE CURSOR_TABLAS;
			/*Parte de los probedures*/
			
		


			DECLARE @CANTIDAD_SP VARCHAR(4000);
			SELECT @CANTIDAD_SP = COUNT(A.SPECIFIC_NAME)
			FROM INFORMATION_SCHEMA.ROUTINES AS A 
			WHERE ROUTINE_TYPE = 'PROCEDURE';

			IF @CANTIDAD_SP <> '0'/*Si al algun procedure creado entra acá*/
			BEGIN 
			
				DECLARE @QUERY2 NVARCHAR(3000) ;
				SET @QUERY2 = '
				DECLARE CURSOR_SP CURSOR SCROLL FOR 
				SELECT SPECIFIC_SCHEMA,SPECIFIC_NAME,ROUTINE_TYPE
				FROM '+ @NOMBREBDD +'.INFORMATION_SCHEMA.ROUTINES WHERE ROUTINE_TYPE =  ' + CHAR(39) + 'PROCEDURE'  + CHAR(39) ;
				EXECUTE sp_executesql @QUERY2
				OPEN CURSOR_SP
				FETCH NEXT FROM CURSOR_SP INTO @NOMBRE_SCHEMA,@NOMBRE_OBJETO,@NOMBRE_TIPO
				WHILE @@FETCH_STATUS = 0 /*Mientras alla tablas se va a recorrer y se van a agregar objetos-tablas a la tabla general*/
				BEGIN
					
					
					
				DECLARE @Select3 NVARCHAR(4000);
				DECLARE @TIENE_PARAM VARCHAR(4000);
				

				SET @Select3 = 'SELECT @TIENE_PARAM = CHARINDEX('+CHAR(39) + '@' + CHAR(39) +' , ROUTINE_DEFINITION )
					FROM ' +@NOMBREBDD+'.INFORMATION_SCHEMA.ROUTINES 
					WHERE SPECIFIC_NAME = ' + CHAR(39) + @NOMBRE_OBJETO + CHAR(39);
				EXECUTE SP_EXECUTESQL	@Select3,
				N'@TIENE_PARAM VARCHAR OUTPUT',
				
				@TIENE_PARAM=@TIENE_PARAM OUTPUT

					
					IF @TIENE_PARAM = '0'
					BEGIN
						INSERT INTO  OBJETOS_DE_LA_BASE_DE_DATOS (NOMBRE_BASE_DE_DATOS,NOMBRE_SCHEMA,NOMBRE_OBJETO,TIPO_DE_DATO,TIENE_PK,TIENE_FK, TIENE_PK_COMPUESTA,TIENE_FK_COMPUESTA)
						VALUES(@NOMBREBDD,@NOMBRE_SCHEMA,@NOMBRE_OBJETO,@NOMBRE_TIPO,'---','---','---','---');	
						INSERT INTO  TABLA_AUDITORIA(NOMBRE_BASE_DE_DATOS,NOMBRE_SCHEMA,NOMBRE_OBJETO,TIPO_DE_DATO,TIENE_PK,TIENE_FK,TIENE_PK_COMPUESTA,TIENE_FK_COMPUESTA)
						VALUES(@NOMBREBDD,@NOMBRE_SCHEMA,@NOMBRE_OBJETO,@NOMBRE_TIPO,'---','---','---','---');	  
					END
					IF @TIENE_PARAM <> '0'
					BEGIN
						INSERT INTO  OBJETOS_DE_LA_BASE_DE_DATOS (NOMBRE_BASE_DE_DATOS,NOMBRE_SCHEMA,NOMBRE_OBJETO,TIPO_DE_DATO,TIENE_PK,TIENE_FK,ACEPTA_PARAMETROS , TIENE_PK_COMPUESTA,TIENE_FK_COMPUESTA)
						VALUES(@NOMBREBDD,@NOMBRE_SCHEMA,@NOMBRE_OBJETO,@NOMBRE_TIPO,'---','---','Si','---','---');
						INSERT INTO  TABLA_AUDITORIA (NOMBRE_BASE_DE_DATOS,NOMBRE_SCHEMA,NOMBRE_OBJETO,TIPO_DE_DATO,TIENE_PK,TIENE_FK,ACEPTA_PARAMETROS , TIENE_PK_COMPUESTA,TIENE_FK_COMPUESTA)
						VALUES(@NOMBREBDD,@NOMBRE_SCHEMA,@NOMBRE_OBJETO,@NOMBRE_TIPO,'---','---','Si','---','---'); 
					END

					FETCH NEXT FROM CURSOR_SP INTO @NOMBRE_SCHEMA,@NOMBRE_OBJETO,@NOMBRE_TIPO;
				 END 
			END
			CLOSE CURSOR_SP;
			DEALLOCATE CURSOR_SP;
			
			
			
		END 
		/*Realizo el select de la tabla que consulta los datos y la borro si no se va a seguir insertando datos repetidos*/
		SELECT ID_OBJETO AS 'Numero' , NOMBRE_BASE_DE_DATOS AS 'Base de datos', NOMBRE_SCHEMA AS 'Esquema' , NOMBRE_OBJETO AS 'Nombre del objero',
		CASE TIPO_DE_DATO 
		WHEN 'BASE TABLE' THEN 'Tabla'
		ELSE 'Procedimiento'	
		END 
		AS 'Tipo de dato',  TIENE_PK AS '¿Tiene PK?',TIENE_FK AS  '¿Tiene FK?', TIENE_PK_COMPUESTA AS '¿Tiene PK Compuesta?', TIENE_FK_COMPUESTA AS 'Tiene FK Compuesta',
		ACEPTA_PARAMETROS AS '¿Acepta parámetros?'
		FROM OBJETOS_DE_LA_BASE_DE_DATOS WHERE TIPO_DE_DATO <> 'VIEW';
		DROP TABLE OBJETOS_DE_LA_BASE_DE_DATOS;
		COMMIT
	END TRY
	BEGIN CATCH
		ROLLBACK
		INSERT INTO TABLA_ERRORES  (NUMERO_DE_ERROR,MENSAJE_DE_ERROR,FECHA_DE_CREACION ,USUARIO,USUARIO_ID) 
		(SELECT ERROR_LINE(), ERROR_MESSAGE() , SYSDATETIME(),USER_NAME(),USER_ID());
		SELECT 'Error'  + CONVERT(varchar(100), ERROR_LINE())+': ' +  ERROR_MESSAGE() as '---------------------------Upps ah sucecido un error---------------------------------';
	END CATCH
END


EXEC MISP 'AdventureWorks2012';

/*Para consultar las tablas de erroes y auditorias ver las sisguientes tablas*/
SELECT * FROM TABLA_ERRORES;
SELECT * FROM TABLA_AUDITORIA;







